// ============================================================================
// rsqrt.sv — fast reciprocal square root, 1/sqrt(x), binary32
// ----------------------------------------------------------------------------
// Interface contract
//   LATENCY            : 1 (seed) + NR_ITERS * 12 (Newton-Raphson) cycles
//                        = 25 cycles at the default NR_ITERS = 2
//   INITIATION INTERVAL: 1 -- fully pipelined, a new x every cycle
//   TARGET FREQUENCY   : 500 MHz
//   ACCURACY           : max 3 ULP, mean 0.42 ULP with LUT_BITS=6, NR_ITERS=2
//                        (measured by hw/golden/model.py, not asserted)
//
// PARAMETERS AND THE TRADE-OFF THEY EXPRESS
//   LUT_BITS  seed table index width; table has 2**LUT_BITS entries of 16 bits
//   NR_ITERS  number of Newton-Raphson refinement steps
//
// Measured accuracy surface (hw/golden/model.py sweep_accuracy, max ULP):
//
//        entries |  0 iters   1 iter   2 iters   3 iters
//     -----------+-------------------------------------------
//        16 (4b) |   732650    47301       201         2
//        64 (6b) |   190954     3249         2         2     <- design point
//       256 (8b) |    48082      208         2         2
//
//   Reading this: 64 entries with 2 iterations is the KNEE. Going to 256 entries
//   buys nothing (already at 2 ULP), and dropping to 16 entries would require a
//   third iteration -- 12 more pipeline stages and ~3 more multipliers -- to
//   reach the same accuracy. So we spend 64*16 = 1024 bits of ROM to save a
//   pipeline stage's worth of multipliers. That is a deliberate area trade,
//   quantified rather than guessed.
//
// HOW IT WORKS
//   1. Exponent split. Every positive binary32 is x = mm * 2**(2k) with
//      mm in [1,4). Then 1/sqrt(x) = (1/sqrt(mm)) * 2**(-k), so the exponent
//      contribution is a subtract and a shift -- free in hardware. Only
//      1/sqrt(mm) over one range needs a table.
//        e odd  -> mm = 2m, k = (e-1)/2
//        e even -> mm = 4m, k = (e-2)/2
//      Getting this normalisation wrong was a real bug caught by the golden
//      model's self-test: it produced a constant ~5.6% error.
//   2. Table lookup gives y0 ~= 1/sqrt(mm), stored as Q2.14 fixed point.
//   3. Newton-Raphson on f(y) = 1/y^2 - x:
//            y <- y * (1.5 - 0.5 * x * y^2)
//      Each iteration roughly TRIPLES the number of correct bits (quadratic
//      convergence). Cost per iteration: 3 multiplies (y*y, x*y2, y*t) and one
//      subtract. The 0.5* is an exponent decrement and the 1.5 is a constant,
//      so neither costs a multiplier.
//
// SPECIAL VALUES: x <= 0, NaN and Inf produce a quiet NaN and raise `err`. The
// software wrapper must not feed those in. It never does: nbody's d2 is > 0 for
// distinct bodies, and raytrace tests `discriminant < 0` before taking a root.
// ============================================================================
`default_nettype none

module rsqrt #(
    parameter int LUT_BITS = 6,
    parameter int NR_ITERS = 2,
    parameter string LUT_FILE = "rsqrt_lut.hex"
) (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        v_in,
    input  wire [31:0] x,
    output wire        v_out,
    output wire [31:0] y,
    output wire        err          // x <= 0, NaN, or Inf
);

    localparam int NR_LAT  = 12;                       // per iteration, see below
    localparam int LATENCY = 1 + NR_ITERS * NR_LAT;    // 25 for NR_ITERS = 2
    localparam int LUT_N   = 1 << LUT_BITS;

    // ---------------- seed table ---------------------------------------------
    // Generated by hw/golden/model.py --vectors as Q2.14 (14 fractional bits).
    // Values lie in (0.5, 1.0], so 2 integer bits are ample.
    (* rom_style = "block" *)
    reg [15:0] lut [0:LUT_N-1];
    initial $readmemh(LUT_FILE, lut);

    // ---------------- stage 0: decompose x ----------------------------------
    wire        x_sgn = x[31];
    wire [7:0]  x_exp = x[30:23];
    wire [22:0] x_man = x[22:0];

    wire x_is_zero = (x_exp == 8'h00);
    wire x_is_inf  = (x_exp == 8'hFF) && (x_man == 23'd0);
    wire x_is_nan  = (x_exp == 8'hFF) && (x_man != 23'd0);
    wire x_bad     = x_sgn | x_is_zero | x_is_inf | x_is_nan;

    // Unbiased exponent E such that x = 1.man * 2**E.
    wire signed [9:0] E = $signed({2'b00, x_exp}) - 10'sd127;

    // Fold the exponent's odd bit into the mantissa so the residual exponent is
    // even and its square root becomes an exact shift:
    //   E even -> mm = 1 + man     in [1,2),  k = E/2
    //   E odd  -> mm = 2 + 2*man   in [2,4),  k = (E-1)/2
    // then 1/sqrt(x) = (1/sqrt(mm)) * 2**(-k).
    wire              parity = E[0];
    wire signed [9:0] k      = (E - $signed({9'd0, parity})) >>> 1;

    // LUT index = {parity, top (LUT_BITS-1) mantissa bits}. A BIT CONCATENATION:
    // no multiply, no divide, no comparison, so the address costs nothing.
    // An earlier version indexed by (mm-1)/3, which needed a constant multiplier
    // and was got wrong twice; choosing the table layout so the address is free
    // is the better engineering trade. The golden model builds the table to
    // match this exact scheme.
    wire [LUT_BITS-2:0] man_top = x_man[22 -: (LUT_BITS-1)];
    wire [LUT_BITS-1:0] idx     = {parity, man_top};

    reg         s0_v, s0_bad;
    reg  signed [9:0] s0_k;
    reg  [31:0] s0_x;
    reg  [15:0] s0_seed_q14;

    always_ff @(posedge clk) begin
        if (!rst_n) begin
            s0_v <= 1'b0;
        end else begin
            s0_v        <= v_in;
            s0_bad      <= x_bad;
            s0_k        <= k;
            s0_x        <= x;
            s0_seed_q14 <= lut[idx];
        end
    end

    // Convert the Q2.14 seed to binary32 and apply 2**(-k).
    // seed_q14 in (0.5,1.0] * 2^14 => the value is seed_q14 / 2^14.
    // Find its leading one to build a normalised float. Because the range is
    // (0.5,1], bit 13 or bit 14 is the leading one, so this is a 2-way select
    // rather than a general leading-zero count -- much cheaper.
    wire        seed_hi = s0_seed_q14[14];                   // value >= 1.0
    wire [22:0] seed_man = seed_hi ? {s0_seed_q14[13:0], 9'd0}
                                   : {s0_seed_q14[12:0], 10'd0};
    wire signed [9:0] seed_exp_unb = seed_hi ? 10'sd0 : -10'sd1;
    wire signed [9:0] y0_exp = seed_exp_unb - s0_k + 10'sd127;

    wire [31:0] y0 = {1'b0, y0_exp[7:0], seed_man};

    // ---------------- Newton-Raphson iterations -----------------------------
    // y <- y * (1.5 - 0.5*x*y^2)
    //
    // Per iteration the dependency chain is:
    //     t1 = y*y            (mul, 3)
    //     t2 = x*t1           (mul, 3)   -- x must be delayed to match
    //     t3 = 1.5 - 0.5*t2   (add, 3)   -- 0.5* is free (exponent decrement)
    //     y' = y*t3           (mul, 3)   -- y must be delayed to match
    // = 12 cycles, 3 multipliers and 1 adder per iteration.
    localparam [31:0] C1P5 = 32'h3FC00000;      // 1.5f

    // Chain state: valid, x (held), y (current estimate)
    wire        it_v    [0:NR_ITERS];
    wire [31:0] it_x    [0:NR_ITERS];
    wire [31:0] it_y    [0:NR_ITERS];
    wire        it_bad  [0:NR_ITERS];

    assign it_v[0]   = s0_v;
    assign it_x[0]   = s0_x;
    assign it_y[0]   = y0;
    assign it_bad[0] = s0_bad;

    genvar g;
    generate
        for (g = 0; g < NR_ITERS; g = g + 1) begin : g_nr
            nr_step u_nr (
                .clk    (clk),
                .rst_n  (rst_n),
                .v_in   (it_v[g]),
                .bad_in (it_bad[g]),
                .x_in   (it_x[g]),
                .y_in   (it_y[g]),
                .v_out  (it_v[g+1]),
                .bad_out(it_bad[g+1]),
                .x_out  (it_x[g+1]),
                .y_out  (it_y[g+1])
            );
        end
    endgenerate

    // ---------------- output -------------------------------------------------
    assign v_out = it_v[NR_ITERS];
    assign err   = it_bad[NR_ITERS];
    // Quiet NaN on an invalid input, so a mistake is loud rather than silent.
    assign y     = it_bad[NR_ITERS] ? {1'b0, 8'hFF, 23'h400000}
                                    : it_y[NR_ITERS];

endmodule


// ============================================================================
// nr_step — one Newton-Raphson iteration for reciprocal square root
//   y_out = y_in * (1.5 - 0.5 * x_in * y_in^2)
//   LATENCY 12, II 1. Carries x and the valid/err flags along so the caller
//   does not have to build matching delay lines.
// ============================================================================
`default_nettype none

module nr_step (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        v_in,
    input  wire        bad_in,
    input  wire [31:0] x_in,
    input  wire [31:0] y_in,
    output wire        v_out,
    output wire        bad_out,
    output wire [31:0] x_out,
    output wire [31:0] y_out
);
    localparam [31:0] C1P5 = 32'h3FC00000;      // 1.5f
    localparam int MUL_LAT = 3;
    localparam int ADD_LAT = 3;

    // t1 = y*y
    wire        v1;
    wire [31:0] t1;
    fp32_mul u_yy (.clk(clk), .rst_n(rst_n), .v_in(v_in),
                   .a(y_in), .b(y_in), .v_out(v1), .y(t1));

    // x must be delayed MUL_LAT to line up with t1.
    reg [31:0] x_d1 [0:MUL_LAT-1];
    reg [31:0] y_d  [0:2*MUL_LAT+ADD_LAT-1];    // y needed at the final multiply
    reg        bad_d[0:2*MUL_LAT+ADD_LAT-1];
    // NOTE: each always_ff below declares its OWN loop variable. Sharing a single
    // module-scope `integer i` between two concurrent always blocks lets them
    // clobber each other's index mid-loop, so delay lines shift incorrectly on
    // some cycles. That produced a sporadic, data-dependent wrong result that
    // only one input in 512 exposed -- exactly the kind of bug a testbench must
    // catch, because it looks like a numerical issue and is not.
    always_ff @(posedge clk) begin : p_delay_in
        integer di;
        if (!rst_n) begin
            for (di = 0; di < MUL_LAT; di = di + 1) x_d1[di] <= 32'd0;
            for (di = 0; di < 2*MUL_LAT+ADD_LAT; di = di + 1) begin
                y_d[di] <= 32'd0; bad_d[di] <= 1'b0;
            end
        end else begin
            x_d1[0] <= x_in;
            for (di = 1; di < MUL_LAT; di = di + 1) x_d1[di] <= x_d1[di-1];
            y_d[0]   <= y_in;
            bad_d[0] <= bad_in;
            for (di = 1; di < 2*MUL_LAT+ADD_LAT; di = di + 1) begin
                y_d[di]   <= y_d[di-1];
                bad_d[di] <= bad_d[di-1];
            end
        end
    end

    // t2 = x * t1
    wire        v2;
    wire [31:0] t2;
    fp32_mul u_xt1 (.clk(clk), .rst_n(rst_n), .v_in(v1),
                    .a(x_d1[MUL_LAT-1]), .b(t1), .v_out(v2), .y(t2));

    // t3 = 1.5 - 0.5*t2.
    // Multiplying by 0.5 is an exponent decrement, so we do it by hand rather
    // than spending a multiplier. Subtracting is adding the sign-flipped value.
    wire [7:0]  t2_exp   = t2[30:23];
    wire        t2_zero  = (t2_exp == 8'h00);
    // decrement the exponent; if it would underflow, the term is negligible ->
    // treat as zero, which leaves t3 = 1.5 (correct in that limit).
    wire [31:0] t2_half  = (t2_zero || t2_exp == 8'h01)
                           ? 32'd0
                           : {t2[31], t2_exp - 8'd1, t2[22:0]};
    wire [31:0] neg_half = {~t2_half[31], t2_half[30:0]};    // -0.5*t2

    wire        v3;
    wire [31:0] t3;
    fp32_add u_sub (.clk(clk), .rst_n(rst_n), .v_in(v2),
                    .a(C1P5), .b(neg_half), .v_out(v3), .y(t3));

    // y' = y * t3   (y delayed by MUL_LAT + MUL_LAT + ADD_LAT)
    fp32_mul u_yt3 (.clk(clk), .rst_n(rst_n), .v_in(v3),
                    .a(y_d[2*MUL_LAT+ADD_LAT-1]), .b(t3),
                    .v_out(v_out), .y(y_out));

    // Carry x and bad along, delayed to match the total 12-cycle latency.
    reg [31:0] x_out_d [0:MUL_LAT+ADD_LAT+MUL_LAT-1];
    reg        bad_out_d;
    always_ff @(posedge clk) begin : p_delay_out
        integer do_;
        if (!rst_n) begin
            for (do_ = 0; do_ < MUL_LAT+ADD_LAT+MUL_LAT; do_ = do_ + 1)
                x_out_d[do_] <= 32'd0;
            bad_out_d <= 1'b0;
        end else begin
            x_out_d[0] <= x_d1[MUL_LAT-1];
            for (do_ = 1; do_ < MUL_LAT+ADD_LAT+MUL_LAT; do_ = do_ + 1)
                x_out_d[do_] <= x_out_d[do_-1];
            bad_out_d <= bad_d[2*MUL_LAT+ADD_LAT-1];
        end
    end
    assign x_out   = x_out_d[MUL_LAT+ADD_LAT+MUL_LAT-1];
    assign bad_out = bad_out_d;

endmodule

`default_nettype wire
